apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-provisioner.fullname" . }}
  labels:
    {{- include "grafana-provisioner.labels" . | nindent 4 }}
data:
  tenants: |-
    ---
    tenants:
      {{- toYaml .Values.tenants | nindent 6 }}
