apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "grafana-provisioner.fullname" . }}
  labels:
    {{- include "grafana-provisioner.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch"]
