apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grafana-provisioner.fullname" . }}
  labels:
    {{- include "grafana-provisioner.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-provisioner.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "grafana-provisioner.fullname" . }}
