apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-provisioner.fullname" . }}
  labels:
    {{- include "grafana-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  configuration: |-
    k8s_namespace: {{ .Release.Namespace }}

    grafana_url: {{ .Values.grafana.url }}
    grafana_username: {{ .Values.grafana.username }}
    grafana_password: {{ .Values.grafana.password }}
    grafana_environment: {{ .Values.grafana.environment }}

    ldap_host: {{ .Values.grafana.ldap.host }}
    ldap_bind_dn: {{ .Values.grafana.ldap.bind_dn }}
    ldap_bind_password: {{ .Values.grafana.ldap.bind_password }}
    ldap_base_dn: {{ .Values.grafana.ldap.base_dn }}
