# Default values for helm-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tjuerge/grafana-provisioner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

command: '["ansible-playbook", "provision-grafana.yml"]'
args: '["-vv", "-e k8s_environment=test"]'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


grafana:
  url: http://grafana/
  username: admin
  password: changeme
  # The environment name ("test" or "prod") is used as suffix for the datasource tenant id
  environment: "test"

  ldap:
      host: directory.acme.com
      bind_dn: cn=LDAP,OU=Users,DC=acme,DC=com
      bind_password: changeme
      base_dn: OU=Tenants,DC=acme,DC=com


tenants: {}
# To specify the tenant configuration (ideally it's provided in its own value file), uncomment
# the following, adjust them as necessary, and remove the curly braces after 'tenants:'.
# - name: tenant1
#    ldap_group_mappings:
#      - cn: cn=Editors,OU=Tenant1,OU=Tenants,DC=acme,DC=com
#        role: Editor
#      - cn: cn=Viewers,OU=Tenant1,OU=Tenants,DC=acme,DC=com
#        role: Viewer
#  - name: tenant2
#    ldap_group_mappings:
#      - cn: cn=Editors,OU=Tenant2,OU=Tenants,DC=acme,DC=com
#        role: Editor
#      - cn: cn=Viewers,OU=Tenant2,OU=Tenants,DC=acme,DC=com
#        role: Viewer
